name: CI

on:
  push:
    branches:
    - master
    - staging
    - trying
  pull_request:
    branches:
    - master

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--deny warnings"

jobs:
  test:
    strategy:
      matrix:
        rust:
          - 1.8.0
          - stable
          - nightly
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "--deny warnings"
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      if: matrix.rust != '1.8.0'  # too old to build criterion
      run: cargo test --all --all-targets

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt
    - name: Check code formatting
      run: cargo fmt -- --check
